### PR TITLE
Initial setup of WRF-runner

### PR DESCRIPTION
**Pull request by Peter9192**
This adds a script and proposed workflow for running WPS/WRF. 

* Namelists for our default setup are stored with this repo, so they are under version control
* Each run gets its own dedicated directory outside of the WRF source code and also outside of this repo, so source code stays clean and under version control, and experiments inputs/outputs are isolated from one another.

Notes

* Currently the included namelist only work partially (for domain 1)
* Many todo's listed in README. Those are for future PRs.

To review this:

Check that you can run the script both on the login node (kill the job once it reaches WRF) and as a batch job through slurm, and that it reaches the command to execute WRF. 

Currently WRF fails because there is an issue with the namelist; fixing the namelist can be part of a future issue.

### CODE REVIEW

**Review by ClaireDons — CHANGES_REQUESTED** [review]
The code fails for me when running geogrid.exe as I had another geogrid table linked. Once I changed my namelist.wps, the program ran with no issues. So, I think that it would be good to add a line which explicitly links the geogrid table required in wrf-runner.sh. 

Just as a note, both geogrid.exe and metgrid.exe failed silently, which made identifying where the program failed difficult. This would need to be addressed within those programs though.

**Comment by Peter9192** [comment]
> The code fails for me when running geogrid.exe as I had another geogrid table linked.

I can reproduce this e.g. with `ln -sf GEOGRID.TBL.FIRE GEOGRID.TBL` This gives: 

```
+ /home/pkalverla1/wrf-model/WPS/geogrid.exe
Parsed 50 entries in GEOGRID.TBL
Processing domain 1 of 1
ERROR: Could not open /projects/0/prjs0914/wrf-data/default/static/WPS_GEOG/landfire_data/index
+ /home/pkalverla1/wrf-model/WPS/ungrib.exe
```

Indeed it happily continues to run ungrib. Geogrid returns a 0 exit status despite the logged ERROR. Same for metgrid later on.

**Comment by Peter9192** [comment]
For now I've linked the ARW table. We could consider to ship our own geogrid table with this WRF-runner in the future, depending on whether it needs to be customized (much).

**Comment by Peter9192** [comment]
The error originates here:

https://github.com/wrf-model/WPS/blob/5a2ae63988e632405a4504cfb143ce7f0230a7a0/geogrid/src/source_data_module.F#L866-L878

The `ERROR` level is handled in `mprintf`:
https://github.com/wrf-model/WPS/blob/5a2ae63988e632405a4504cfb143ce7f0230a7a0/geogrid/src/module_debug.F#L316-L324

I suspect adding an integer to the `stop` command or using `error stop` instead could potentially fix this. See e.g. [this thread](https://fortran-lang.discourse.group/t/stop-with-non-zero-exit-status/2062/11)

**Comment by Peter9192** [comment]
Opened https://github.com/wrf-model/WPS/issues/252 to see if this can be addressed in WPS.

**Comment by Peter9192** [comment]
@ClaireDons could you have another go at this and approve/merge if ok? Then you can follow up with updated namelists, and getting w2w into the workflow.

**Review by ClaireDons — APPROVED** [review]

**Pull request merged**
